# Generated by Django 4.2.19 on 2025-03-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inference',
            name='dta_method',
            field=models.CharField(blank=True, choices=[('TT', 'Maximum-likelihood using TreeTime'), ('PH', 'Parsimony using phangorn')], max_length=2, null=True),
        ),
    ]
