# Generated by Django 4.2.19 on 2025-03-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0003_alter_inference_random_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplesallocation',
            name='spatial_strategy',
            field=models.CharField(blank=True, choices=[('US', 'Uniform allocation in proportion to number of samples'), ('UC', 'Uniform allocation in proportion to number of cases'), ('IUC', 'Uniform allocation in inverse proportion to number of cases'), ('UP', 'Uniform allocation in proportion to population size'), ('IUP', 'Uniform allocation in inverse proportion to population size'), ('EV', 'Even allocation of samples across demes')], default='UC', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='samplesallocation',
            name='temporal_strategy',
            field=models.CharField(blank=True, choices=[('US', 'Uniform allocation in proportion to number of samples'), ('UC', 'Uniform allocation in proportion to case incidence'), ('IUC', 'Uniform allocation in inverse proportion to case incidence'), ('EV', 'Even allocation of samples across time'), ('EN', 'Earliest N samples'), ('LN', 'Latest N samples')], default='UC', max_length=3, null=True),
        ),
    ]
