# Generated by Django 4.2.19 on 2025-03-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0004_alter_samplesallocation_spatial_strategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inference',
            name='depth_field',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
