# Generated by Django 4.2.19 on 2025-03-30 14:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0005_inference_depth_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inference',
            name='depth_field',
        ),
        migrations.AddField(
            model_name='inference',
            name='inference_chain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.UUIDField(), blank=True, null=True, size=None),
        ),
    ]
