# Generated by Django 4.2.19 on 2025-03-30 14:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0006_remove_inference_depth_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inference',
            name='inference_chain',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, default=list, null=True, size=None),
        ),
    ]
