# Generated by Django 4.2.19 on 2025-04-02 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inferences', '0007_alter_inference_inference_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inference',
            name='samples_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inferences.samplesallocation'),
        ),
    ]
