# Generated by Django 4.2.19 on 2025-03-02 11:05

from django.db import migrations, models
import simulations.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbreak_origin', models.IntegerField(blank=True, null=True)),
                ('beta', models.FloatField(blank=True, null=True)),
                ('gamma', models.FloatField(blank=True, null=True)),
                ('delta', models.FloatField(blank=True, null=True)),
                ('num_demes', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(blank=True, null=True)),
                ('populations', models.JSONField(blank=True, null=True)),
                ('sampling_times', models.JSONField(blank=True, null=True)),
                ('mobility_matrix', models.JSONField(blank=True, null=True)),
                ('case_incidence', models.JSONField(blank=True, null=True)),
                ('migratory_events', models.JSONField(blank=True, null=True)),
                ('populations_file', models.FileField(upload_to=simulations.models.upload_populations_file_path)),
                ('mobility_matrix_file', models.FileField(upload_to=simulations.models.upload_mobility_matrix_file_path)),
                ('trajectory_file', models.FileField(upload_to=simulations.models.upload_trajectory_file_path)),
                ('sampled_tree_file', models.FileField(upload_to=simulations.models.upload_sampled_tree_file_path)),
                ('epi_params_file', models.FileField(upload_to=simulations.models.upload_epi_params_file_path)),
                ('xml_file', models.FileField(upload_to=simulations.models.upload_xml_file_path)),
                ('is_complete', models.BooleanField(default=False)),
            ],
        ),
    ]
