# Generated by Django 4.2.19 on 2025-03-02 11:39

from django.db import migrations, models
import simulations.models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulation',
            name='uuid',
            field=models.UUIDField(default=simulations.models.generate_short_uuid, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
