# Generated by Django 4.2.19 on 2025-03-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0003_alter_simulation_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='name',
        ),
    ]
