# Generated by Django 4.2.19 on 2025-03-21 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0004_remove_simulation_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='beta',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='delta',
        ),
    ]
