# Generated by Django 4.2.19 on 2025-04-02 09:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulations', '0005_remove_simulation_beta_remove_simulation_delta'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
    ]
